### ISSUE TITLE
tag new versions

### ISSUE THREAD

**Issue by xini** [fromholdio/silverstripe-urlsegmenter#2]
Can you please tag new versions with the latest changes on master? 

Also, have you decided on a resolution of v1/v2 tags?

Cheers

**Comment by xini** [comment]
any updates on this?

**Comment by dizzystuff** [comment]
Hey @xini , thanks for the nudge on this.

* v2 supercedes v1. Due to some bungling here, 1.1.0 and 2.0.1 are equal. Moving forward however, only 2.x will receive patches/fixes if necessary.
* v3.0.0 has been released. This contains the overhaul that had been sitting in master. This is now the current version.

Cheers

**Comment by xini** [comment]
awesome, thanks!
